### ISSUE TITLE
Imagenet models tar error, md5 values need to be provided

### ISSUE THREAD

**Issue by persistz** [ParagonLight/dissector#3]
For different files, when I use tar to unpack, the following error always appears:

tar: Unrecognized archive format

I have tested on different OS(Windows 10, Linux Arch, and macOS) with different model files(VGG and ResNet),

If these files can be used normally locally, could you provide MD5 hash values for verification? 
These values can help users to troubleshoot download problems caused by network failures.

Thanks.

**Comment by ParagonLight** [comment]
Hi Zhe,

Please directly use torch.load() to load the model, since the model files named *.pth.tar are saved by torch.save(). They are not unpack-able files actually.

**Comment by persistz** [comment]
Hi Jingwei,

Thanks for your reply! 😀

Closed.

BTW, I think in the ReadMe file 'pip install ... progressbar' should be modified as 'progress', since this is just a typo, I did not submit a PR, you can check and fix it.

**Comment by ParagonLight** [comment]
Thx, I will check this ASAP.
